apiVersion: apps/v1
kind: deployment
metadata:
  name: {{ .values.component_name }}
  labels:
    app: guestbook
    tier: {{ .values.component_name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: {{ .values.component_name }}
      type: rs
  template:
    metadata:
      labels:
        tier: {{ .values.component_name }}
        type: rs
    spec:
      containers:
      - name: nginx
        image: nginx